---
- hosts: all
  become: true
  tasks:
  - name: Update Ubuntu
    apt: update_cache=yes upgrade=dist
    when: ansible_os_family == "ubuntu"
  - name: Update CentOS
    apt: name=* update_cache=yes
    when: ansible_os_family == "CentOS"